data:
  test_mics: [con]
  test_zoom: True
  dataloader:
    label_path: dataset/wav/THAISER/labels.csv
    agreement: 0.71
    smoothing_param: 0.
    use_soft_target: False
    include_fru: True
    include_zoom: False
    train_mic: con

featurizer:
  feature_type: fbank
  feature_param:
    num_mel_bins: &n_mel 64
    frame_length: 25
    frame_shift: 10
    low_freq: 0
    high_freq: 8000
    sample_frequency: 16000
  vtlp_range: [0.9, 1.1]

packer:
  max_len: &max_len 3
  pad_mode: dup
  stats_path: null

model:
  n_channels: [64, 64, 128, 128]
  kernel_size: [5, 3, 3, 3]
  pool_size: [2, 2, 2, 2]
  lstm_unit: 128
  
train:
  batch_size: 32
  n_iteration: 5
  exp_path: log/baseline/baseline
  trainer_param:
    progress_bar_refresh_rate: 0  # disable logging
    weights_summary: null  # disable logging
    max_epochs: 40
    gpus: [0]
    
