data:
  test_zoom: True
  dataloader:
    label_path: dataset/wav/IEMOCAP_full_release/pruned_labels.csv
    use_soft_target: True
    use_all_emotions: False
    turn_type: all
    cross_corpus:
      thaiser: dataset/wav/THAISER/pruned_labels.csv
      emodb: dataset/wav/emodb/labels.csv
      emovo: dataset/wav/EMOVO/labels.csv

featurizer:
  feature_type: fbank
  feature_param:
    num_mel_bins: &n_mel 40
    frame_length: 50
    frame_shift: 10
    low_freq: 0
    high_freq: 8000
    sample_frequency: 16000
  vtlp_range: [0.9, 1.1]

packer:
  max_len: &max_len 3
  pad_mode: dup
  stats_path: null

model:
  n_channels: [64, 64, 128, 128]
  kernel_size: [5, 3, 3, 3]
  pool_size: [2, 2, 2, 2]
  lstm_unit: 128
  
train:
  batch_size: 64
  learning_rates: 0.0001
  exp_path: iemocap-playground/iemocap-crosscorpus_all_prune_speaker
  n_iteration: 5
  trainer_param:
    max_epochs: 30
    gpus: [0]
    
